image: python:3.5.1

pipelines:
  branches:
    staging:
      - step:
          # set AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_DEFAULT_REGION as environment variables
          name: Deploy to AWS
          deployment: staging   # set to test, staging or production
          # trigger: manual  # uncomment to have a manual step
          image: atlassian/pipelines-awscli
          script:
            - aws deploy push --application-name PipePay --s3-location s3://pipepay/pp --ignore-hidden-files
            - aws deploy create-deployment --application-name PipePay --s3-location bucket=pipepay,key=pp,bundleType=zip --deployment-group-name stage