image: node:6.9.4

pipelines:
  branches:
    develop:
      - step:
          name: Server Test
          caches:
            - node
          services: 
            - mongo
          script:
            - npm install
            - npm run server:test
    staging:
      - step:
          name: Deploy to AWS
          deployment: staging
          image: atlassian/pipelines-awscli
          script:
            - aws deploy push --application-name PipePay --s3-location s3://pipepay/pp --ignore-hidden-files
            - aws deploy create-deployment --application-name PipePay --s3-location bucket=pipepay,key=pp,bundleType=zip --deployment-group-name stage