version: '3.7'

services:

  pipepay:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - NODE_ENV=staging
        - PORT=4545
        - DB_HOST=mongodb
        - PAYSTACK_SECRET=sk_test_ef208dee35b39342cf35bf961ec6cb19ebc2f94c
        - PAYSTACK_PUBLIC_KEY=pk_test_255dd0432fd98c3983285837334c8a4f002b6f31
        - COGNITO_AUD=4dmr7et8m2ii9490eh8lh3kk70
        - COGNITO_USER_POOL_ID=us-east-2_vAgT6Wlzp
        - ZOHO_EMAIL=hello@pipepay.africa
        - ZOHO_PASSWORD=WebWizard#1
        - JWT_SECRET=secret
        - AWS_ACCESS_KEY_ID=AKIA2FQCSKOO7VFCTTYV
        - AWS_SECRET_KEY=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
    ports:
      - "4545:4545"
    volumes:
      - "./src:/usr/src/pipepay/src"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - default
